import {NextIntlClientProvider, hasLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import type { Metadata } from "next";
import "@/app/globals.css";
import Header from '@/Components/Header';
import Footer from '@/Components/Footer';
import Head from 'next/head';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
};

export default async function RootLayout({children, params}: Props) {

  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang="en">
      <body>
        <Head>
          <title>PokedexNacional - PokeApp</title>
          <meta name="Explora la Pokédex de la primera generación: un listadocompleto de Pokémon con sus características y detalles
          principales." content="Esta es una descripción de la página." />
        </Head>
          <NextIntlClientProvider>
            <Header></Header>
            <main>
              {children}
            </main>
            <Footer></Footer>
          </NextIntlClientProvider>
      </body>
    </html>
  );
}
